apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-http-request
  namespace: rhdh
  title: "Scaffolder Backend Module HTTP Request"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-http-request"
  # Tag: bs_1.54.9__5.9.0, Build date: 2026-05-26T12:36:42Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-scaffolder-backend-module-http-request@sha256:b0e59d7482187ec813458c5bad1a869d6def9d42b4a61e4422af148ae20ca578"
  version: 5.9.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Roadie
  support: generally-available
  lifecycle: active
  partOf:
    - http-request-scaffolder-action
  appConfigNotRequired: true
  appConfigExamples: []
